Himil/bag from images
embarktrucks/kalibr pull request #1
Opened 2020-09-14 19:05 UTC by HimilSheth

2020-09-21 20:25 UTC, erik-embarktrucks requested changes
Could you update the description a bit with how this works. Also see the comments, mostly about removing commented out code

2020-09-21 20:25 UTC, erik-embarktrucks commented on aslam_cv/aslam_cameras/include/aslam/cameras/GridCalibrationTargetGeneral.hpp
> +  void setPoints(const Eigen::MatrixXd &gridpoints);
are these pixels or in 3d? Name variable accordingly

2020-09-21 20:25 UTC, erik-embarktrucks commented on aslam_cv/aslam_cameras/include/aslam/cameras/GridCalibrationTargetGeneral.hpp
> +  void setPoints(const Eigen::MatrixXd &gridpoints);
Also add docstring

2020-09-21 20:25 UTC, erik-embarktrucks commented on aslam_cv/aslam_cameras/src/GridCalibrationTargetGeneral.cpp
> +  // for (unsigned int r = 0; r < rows; r++)
Remove commented out code

2020-09-21 20:25 UTC, erik-embarktrucks commented on aslam_cv/aslam_cameras/src/GridCalibrationTargetGeneral.cpp
> +  // if (_options.showExtractionVideo) {
remove commented out code

2020-09-21 20:25 UTC, erik-embarktrucks commented on aslam_cv/aslam_cameras/src/GridCalibrationTargetGeneral.cpp
> +  // for (unsigned int r = 0; r < _rows; r++)
remove commented out code

2020-09-21 20:25 UTC, erik-embarktrucks commented on aslam_cv/aslam_cameras/src/GridCalibrationTargetGeneral.cpp
> +  // extract the circle grid corners
remove commented out code, and add a comment in the header that this function actually doesn't do anything.

I am a bit confused here also. Shouldn't outCornerObserved be filled in?

2020-09-21 20:25 UTC, erik-embarktrucks commented on aslam_cv/aslam_cv_python/src/GridCalibration.cpp
> +  // Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> _points;
remove commented out code

2020-09-21 20:25 UTC, erik-embarktrucks commented on aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/MulticamGraph.py
> +		return self.G.adhesion()
looks like wrong indentation here

2020-09-21 20:25 UTC, erik-embarktrucks commented on aslam_offline_calibration/kalibr/python/reproject.py
> +import numpy as np
What does this file do?

2020-09-21 23:22 UTC, HimilSheth commented on aslam_cv/aslam_cameras/src/GridCalibrationTargetGeneral.cpp
> +  // extract the circle grid corners
It's filled externally from all_image_corners in the script. I checked throughout the code and this function is only called from couple of places. One thing to keep in mind though that the Kalibr camera validator script would be broken because of this because it assumes that we are using kalibr detector as well. In an ideal situation, I will override that script as well but for now it's all good

2020-09-21 23:22 UTC, HimilSheth commented on aslam_offline_calibration/kalibr/python/reproject.py
> +import numpy as np
Removed the file.

2020-09-21 23:29 UTC, HimilSheth commented on aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/MulticamGraph.py
> +		return self.G.adhesion()
It's actually a fix so the kalibr code can work for single cameras. More details
https://github.com/ethz-asl/kalibr/pull/358

2020-09-22 00:00 UTC, HimilSheth commented on aslam_cv/aslam_cameras/include/aslam/cameras/GridCalibrationTargetGeneral.hpp
> +  void setPoints(const Eigen::MatrixXd &gridpoints);
Done

2020-09-22 00:01 UTC, HimilSheth commented on aslam_cv/aslam_cameras/src/GridCalibrationTargetGeneral.cpp
> +  // for (unsigned int r = 0; r < rows; r++)
Done

2020-09-22 00:01 UTC, HimilSheth commented on aslam_cv/aslam_cameras/src/GridCalibrationTargetGeneral.cpp
> +  // if (_options.showExtractionVideo) {
Done

2020-09-22 00:01 UTC, HimilSheth commented on aslam_cv/aslam_cameras/src/GridCalibrationTargetGeneral.cpp
> +  // for (unsigned int r = 0; r < _rows; r++)
Done

2020-09-22 00:01 UTC, HimilSheth commented on aslam_cv/aslam_cv_python/src/GridCalibration.cpp
> +  // Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> _points;
Done

2020-09-22 17:08 UTC, erik-embarktrucks commented on aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/MulticamGraph.py
> +		return self.G.adhesion()
It still looks wrong

2020-09-22 17:09 UTC, erik-embarktrucks approved these changes

2020-09-22 20:27 UTC, merged